const ActionTypes = {
  SET_SAMPLE_RESPONSE: "SET_SAMPLE_RESPONSE",
  UPDATE_PROGRESS_SAMPLE: "UPDATE_PROGRESS_SAMPLE",
  BEFORE_PROGRESS_SAMPLE: "BEFORE_PROGRESS_SAMPLE",
  PROGRESS_SAMPLE_DONE: "PROGRESS_SAMPLE_DONE",
  ON_CHAT_MSG: "ON_CHAT_MSG"
};

export default ActionTypes;